### ISSUE TITLE
Tracks playing much faster 

### ISSUE THREAD

**Issue by efrentgn** [pideck/pideck#101]
I built pideck 0.2 with the following items:

- Raspberry Pi B+
- 'Official' 7" touchscreen
- Behringer UCA222 soundcard
- Pionner CDJ800MK2 CDPlayer

It boots okay and loads usb but when I press play this is what happens:
 - Bmp's go up crazy
 - Track plays much faster (around 2x)
 - A loud whiste is heard that dissappears when the soundcard is off, although it keeps working.. 

Anybody with the same issue? Thanks in advance.

**Comment by danielhjames** [comment]
If you're hearing a whistle from a timecode CD, that suggests your soundcard is passing the input direct to the output. Which position is the Monitor switch in, please?

As for the track playing fast, are you using a Serato timecode CD?

**Comment by efrentgn** [comment]
Whistle issue seems to be solved.

Timecode CD was Traktor (first release) not Serato. 

Thank you very much, I really appreciate your help.

**Comment by danielhjames** [comment]
We recommend using Serato timecode with xwax and PiDeck, it can be downloaded if you provide an email address: https://serato.com/controlcd 
It works fine with all CD players when burned as audio rather than a data CD. More recent CDJ's may be able to play the wav files directly.

**Comment by efrentgn** [comment]
Wow, now is working great with Serato timecode! 

Thank you very much indeed!

**Comment by danielhjames** [comment]
Cool, please post a video of your setup on YouTube and let us know the URL so we can add it to our community playlist :-)

**Comment by danielhjames** [comment]
I have opened #103 to support Traktor timecode in future, although Serato timecode will continue to be recommended for best performance.

**Comment by charlesreid1** [comment]
> We recommend using Serato timecode with xwax and PiDeck, it can be downloaded if you provide an email address:https://serato.com/controlcdIt works fine with all CD players when burned as audio rather than a data CD. More recent CDJ's may be able to play the wav files directly.

Note, link should be https://serato.com/controlcd

**Comment by danielhjames** [comment]
Thanks @charlesreid1 - looks like GitHub's wrapping of emails broke the link!
