### ISSUE TITLE
NOVATION DICER NOT RECOGNISED ON STARTUP WITH HERCULES MK2.

### ISSUE THREAD

**Issue by raynessupreme** [pideck/pideck#105]
Me Again (apologies.

This time I managed to cop a Hercules MK2 off eBay for a steal. I got it working in Ubuntu with a simple xwax -l ~/audio -a Mk2_pair1 -a Mk2_pair2

However I had some issues with PiDeck. After wondering why the soundcard wasn't recognised given all the .asoundrc info is hard written to the PiDeck OS, I unplugged my Novation Dicer on startup and the soundcard worked. I mucked about with the PiDeck script but couldn't get the Dicer and The MK2 to play ball on startup. It would work sometimes If I opened a terminal and and then ran /usr/share/pideck/pideck, but even this was temperamental and wouldn't always work.

My query is, given that the Dicer Script is already in the PiDeck system and works on a restart (sometimes), why is not being recognised on startup and causing problems?

Here is what is in the Terminal when I run /usr/share/pideck/pideck with everything connected:

**xwax: no process found
jackd: no process found
/usr/bin/jackd: no process found
lxpanel: no process found

Available sound cards:
0 [Mk2 ]: USB-Audio - Hercules DJ Console Mk2 Hercules Hercules DJ Console Ml2 at usb-3f980000, usb-1.3, full speed
l [Dicer ]: USB-Audio - Dicer Novation DMS Ltd Dicer at usb-3f98000.usb-1.5, low speed

FOUND Hercules DJ Console Mk2

Number of supported cards found: 1

setting output levels to maximum:

amixer: Unable to find simple control 'PCM',0

Using -a Mk2_pair1 -a Mk2_pair2 with 04ms buffer

FOUND Novation Dicer

Left buttons: soundcard is set to = 'twindeck'
Right buttons: soundcard is set to = 'twindeck'

Now we are ready to start xwax:

xWax copyright...

Initialising Deck 0 (Mk2_pair1)...
ALSA lib pcm_dsnoop.c:638:(snd_pcm_dsnoop_open) unable to open slave
ALSA open: no such file or directory
Failed to open device for capture**

Someone will no doubt look at this and see a painfully simple fix. However I cannot quite fathom how things are detected but won't run, especially with the Dicer disconnected, and sometimes reconnected and the /usr/share/pideck/pideck script ran (that occasionally works)

I like the Hercules Mk2. It is louder than my Mixvibes uMix44 and I can appreciate the hardware bypass button. Unfortunately when playing regular vinyl through it, it is incredibly bassy. That was from both ubuntu xWax and the PiDeck. It may be the needle that could be causing the issue. I swapped out my Ortofon Concorde Scatch MK2 to a Stanton 500 and the bass issues went away.

Many Thanks in advance.

Shaun.

**Comment by danielhjames** [comment]
Hi @raynessupreme is the ~/.asoundrc file present and containing the following? https://raw.githubusercontent.com/pideck/pideck/master/Mk2.asound.conf

**Comment by raynessupreme** [comment]
Hi @danielhjames,

Yes, I believe the ~/.asoundrc file is present and correct. I did briefly skim through it and it seemed to match the one on the xWax website, I can confirm the MK2 works well, albeit the excess bass in regular vinyl mode. 

I'm still puzzled as to why my PiDeck setup won't automatically boot up with the MK2 and Dicers recognised and working. As far as I can see everything is initially recognised, but needs a tweaked configuration to work (if it will all work full stop).

Thank you for helping me. Hopefully we can all get the bottom of this. I shall try Mucking About with it again this evening. 

Shaun.

**Comment by raynessupreme** [comment]
Hi again @danielhjames.

It would seem the PiDeck had the MK2 asoundrc file set as 'HW:1' rather than 'MK2:1'.

Edited, saved and everything boots up as it should. I knew it would be something simple. Haha! Many thanks once again.

**Comment by danielhjames** [comment]
Thanks @raynessupreme this should be fixed in https://github.com/pideck/pideck/commit/95af72662e5f888743c76a4081de2c41279d22b4
