### ISSUE TITLE
Pideck, umix 44 and no touchscreen

### ISSUE THREAD

**Issue by Supercafone** [pideck/pideck#108]
As a relatively green linux user I'm trying to get my b3+ and mixvibes u-mix44 to run pi-deck. I had the sound card working with xwax on a very old netbook a long time ago, but I can't seem to get to the problem on the pi. 

In my efforts I took advice and inspiration from https://github.com/pideck/pideck/issues/93 and https://github.com/pideck/pideck/issues/92, and ran in to similar problems. Unfortunately the solution seem not to be mentioned, or I might be missing it. 

I copied the asoundrc file from my old installation to the pideck, put it in the pideck folder as umix44.asound.conf, refered to it in cards_autodetect the same way it is done for similar 4 channel cards and added a line in sup_cards.conf (I'm not completely sure where this file is used and how it is supposed to be referred, so that might be my problem).  

In some attempts only the buttons load, in others nothing loads or responds but the pideck is still accessible via SSH. The latter case seemed to be caused by syntax errors on my part, but I can't be certain. 

I've also tried starting xwax directly from the command line, and to replace $XCARD by the two pairs, while asoundrc was in the homefolder. In both cases to no avail.

Any thoughts or suggestions on how to move forward will be greatly appreciated! A brute workaround would also do, as this will probably be the only card I'll use for this build. If needed I can add code below, but it seemed excessive to post all files at this moment.

In addition I would like to completely disable the touch buttons, is there a clean way to do this? I'm using a regular 7 inch hdmi monitor and a keyboard for now. I intend to build a nice case and add physical buttons later, so I won't have a need for them in the future. Anyway, first I'll have to get xwax to start.

**Comment by danielhjames** [comment]
Hi @Supercafone the format of `sup_cards.conf` is:

`[soundcard identifier] [buffer size in milliseconds]`

The soundcard identifiers can be found using a command in a terminal such as:
`arecord -l`

To prevent touch buttons from starting, edit the script `cards_autodetect` to comment out the relevant lines which start `/usr/share/pideck/touchscreen_controls_L` and `/usr/share/pideck/touchscreen_controls_R` for the hardware you are using, or the generic configurations on lines 162 and 163. Please see https://github.com/pideck/pideck/blob/master/cards_autodetect

**Comment by Supercafone** [comment]
Thanks a lot @danielhjames, for the reply and all the great work on pideck! Turned out I wasn't (far) of, but missed a "}" in my .asoundrc, which I found by running pideck from terminal while going over everything again. Do I feel stupid! 

Everything starts as it should now and I'll be diving into the physical buttons and tweaking of setup!
