### ISSUE TITLE
not displaying songs

### ISSUE THREAD

**Issue by rastiguey** [pideck/pideck#115]
Hollo everybody,
I m trying to run pideck but i have any problem that dosnt let me do it, does anybody knows what can i do. Thats the message  that the terminal throws me whe i do /usr/share/pideck/pideck

Initialising deck 0 (hw:0)...
ALSA lib pcm_hw.c:1667:(_snd_pcm_hw_open) Invalid value for card
ALSA open: No such file or directory
Failed to open device for captura

**Comment by danielhjames** [comment]
Hi, which audio hardware is connected to the Pi please?

**Comment by rastiguey** [comment]
behringer u-phono ufo202

**Comment by danielhjames** [comment]
What does the output of the command `aplay -l` say please? Is the UFO 202 listed as card 0?

**Comment by rastiguey** [comment]
card1: CODEC [USB AUDIO CODEC], device 0:USB audio [USB audio]
    subdevices:1/1
    subdevice#0: subdevice #0

**Comment by danielhjames** [comment]
Hi @rastiguey this means your UFO202 is being detected as hw:1 instead of the default PiDeck setting of hw:0

Please post the full text output from /usr/share/pideck/pideck or a screenshot.

**Comment by rastiguey** [comment]
hi @danielhjames this is my output, can you see it? 

Talking about the isue of hw:1 how can i set my card as hw:0?

Thanks a lot for your help.

![IMG-4541](https://user-images.githubusercontent.com/36448563/77826747-8d772580-7111-11ea-8d65-4bb7a6d01c78.jpg)

**Comment by danielhjames** [comment]
Hi, are you running the 0.1 version of PiDeck? If so, version 0.2 should work much better for you. You can download version 0.2 from https://github.com/pideck/pideck-distro/releases

**Comment by rastiguey** [comment]
I have tried with the file in your link but still the same problem and the same output of /usr/share/pideck/pideck

**Comment by danielhjames** [comment]
Could you post an image of the screen output using PiDeck version 0.2 please? This should report more information about your soundcard detected.

**Comment by rastiguey** [comment]
For shure here you are i think its the same

![IMG-4571](https://user-images.githubusercontent.com/36448563/77926476-7158bd00-72a6-11ea-92be-130edaaac28d.jpg)

**Comment by danielhjames** [comment]
Hi, that looks like output from version 0.1 again because the version of xwax is 1.6.x. In PiDeck 0.2 the version of xwax should be 1.7.x

**Comment by rastiguey** [comment]
Yeaah finaly i downloaded again the version 1 instead of version 2. thank you so much
Now i think its working 
![IMG-4572](https://user-images.githubusercontent.com/36448563/77944573-7aa25380-72bf-11ea-829d-cf90d58f5bde.jpg)

**Comment by danielhjames** [comment]
Great, have fun! You can adjust the display parameters in the pideck script to fit your monitor.

**Comment by rastiguey** [comment]
Hello again,
I have tried with the serato vinyl and i hear a constantly underground sound like a beep, you know how to fix that?

**Comment by danielhjames** [comment]
Yes, this is a known issue with the UFO202, which needs a simple hardware mod for use with timecode. Please see https://mixxx.org/forums/viewtopic.php?t=2438 and the video at https://www.youtube.com/watch?v=iYIiqVGjcVk for the solution.

**Comment by rastiguey** [comment]
I tried that and now my UFO202 doesnt works, no worry i have purchased one other model that is better.

About adjusting the display parameters how can I do that?

**Comment by danielhjames** [comment]
Sorry to hear that, I hope the new interface works better.

xwax display size is set with the geometry parameter in pixels, for example `-g 630x480` is the default in PiDeck. Please see line 61 of https://github.com/pideck/pideck/blob/master/pideck

**Comment by rastiguey** [comment]
Ok so once i have modified the file, what i should do to load it into the sd card?

**Comment by danielhjames** [comment]
It is easier to modify this file directly on the Pi, where it is installed as `/usr/share/pideck/pideck`
With the touch buttons in focus, you can press F10 on a connected USB keyboard to open a terminal on the PiDeck.

**Comment by rastiguey** [comment]
okay thanks a lot

**Comment by rastiguey** [comment]
yeah that worked, do you kno whow can i change the size of the buttons?

**Comment by rastiguey** [comment]
Excuse me do you know some other cards that work good? there is no stock of the one that i ordered.

**Comment by danielhjames** [comment]
Button sizes are set using `btn.set_size_request` in https://github.com/pideck/pideck/blob/master/touchscreen_controls_L and https://github.com/pideck/pideck/blob/master/touchscreen_controls_R

Personally I now use an M-Audio Torq Conectiv as my audio interface. You can pick them up pretty cheap on eBay, and the outputs are good and loud. Regular USB audio interfaces can work with the PiDeck as long as they are class-compliant, but they are quiet on the output compared to a CDJ.
