### ISSUE TITLE
Cannot connect over SSH to PiDeck?

### ISSUE THREAD

**Issue by obbardc** [pideck/pideck#12]
As the title says, we have never had a problem with the SSH server before; but I have just had a problem with my fresh SD card install. The issue was the RSA and DSA keys on the server.

I insert a service when I generate the distro to regenerate these keys on the first boot. Maybe it's not working?

This needs confirming as a bug.

**Comment by obbardc** [comment]
Just tried with a fresh SD card image; and it works out of the box.

**Comment by andriiburka** [comment]
Hey guys, little problem with SSH here... 
I create ssh file in main directory of mSD card and connected pideck to my router via RJ45 LAN.. with FING app i can scan all router connections IP addresses so i found IP of the PiDeck.. sooo
when i type "ssh \ip_of_the_pideck\" it asks for the password.. How can i know which is it ?
andriiburka@gmail.com

**Comment by danielhjames** [comment]
Hi @andriiburka if you have installed the PiDeck 0.2 image the username is 'pi' and the default password for this user is 'deck'.
