### ISSUE TITLE
Allow more choice of audio settings

### ISSUE THREAD

**Issue by obbardc** [pideck/pideck#15]
This kind of this will be auto-detected; but we could let the user choose the following options:
- buffersize
- software phono preamp
- use of plughw (not sure about this one)

the user would then restart xwax after applying the settings. if there are too many xruns with the buffersize; it could notify the user.

I'm not sure how relevent this would be with our custom soundcard...

**Comment by danielhjames** [comment]
Implemented by @ximae in https://github.com/pideck/pideck/blob/master/cards_autodetect with additional help from @BennPaul, thanks guys!
