### ISSUE TITLE
crackling noise upon loading new track in not running deck

### ISSUE THREAD

**Issue by whome89** [pideck/pideck#153]
Hey there,

decided to open a new one and not spam into the other issue.

Setup: rpi 3b + 5inch touchscreen on gpio & hdmi + pideck + native instruments audio dj 8 interface

the problem:
Everything seems fine, but only when loading a new track into the not running deck there is an audible crackling noise. sometimes at the start of loading process, in the middle - seems random. for me it seems to correlate to the loading/decoding of the tracks.
It does not always appear and behaves differently every time. "not always" meaning every 3 or 4 tracks it works without crackling noise. sometimes the same track is affected upon loading sometimes not. 
it seems also irrelevant what kind of file I try to load, or what size it has (Mp3, Flac, wav from 5mb up to 95mb).

Maybe a power supply issue? i saw other users could eliminate this kind of issue with having a powered usb hub.
so far i treid:

powering the rpi with 5v 2500mA.
setting up the interface with a powered usb hub (5v, 1200mA) also didn’t change anything.
I even put another power source to the touchscreen's power in (5v, 1000mA).
i also tried running the rpi completely withouth touchscreen and controlling only via usb keyboard, still the same.

Anybody ever heard of/had this issue?

–

And another question: does this scope look fine for you guys? This is the shape if audio8 is switched on phono input mode. (In control vinyl mode it basically the same shape but bouncing periodically)
Im asking because sometimes it seem to be a dispersed signal.

It is the first serato control vinyl, side A - brandnew. 
Im also noticing that input leds barely light up if at all on the usb interface. Normal?

You can view the video of scope and mixer setup and NI audio 8 input/output signal here on Vimeo:
https://vimeo.com/896576427

any help apreciated

**Comment by danielhjames** [comment]
Hi @whome89 is your 2500mA power supply the official Raspberry Pi one putting out 5.1 volts? I've seen problems with using third-party supplies. Also it's possible to have ground loops from connecting audio equipment which is powered from different mains sockets.

The oval scope could be a phasing issue. Is your stylus pointing directly downwards when not on the record, or is it pointing off to the side a little? To test for any turntable issues, you can connect a CD player to the audio interface (using the line level input of course) and use the Serato CD image available for download online to burn to a CD-R.

**Comment by whome89** [comment]
no its a china made 5 volts power supply with an on/off switch.

ground loops: tried grounding turntable on my mixer and on the usb interface with no changes.
also running everything from one main socket.

going to try to get an official power supply.
going to try with cd player!

thanks for those hints.

**Comment by whome89** [comment]
update: i ordered a official raspberry charger with 5.1v and 3A and now the issues are gone. unbelievable.
this charger powers the raspberry with gpio touch screen and the audio 8 dj soundcard. 
it is still only sometimes audible if i scroll too fast in the library though.

thanks for the support!

**Comment by danielhjames** [comment]
Glad to hear that is more or less fixed!
