### ISSUE TITLE
Change timecode to another type

### ISSUE THREAD

**Issue by obbardc** [pideck/pideck#17]
For now we only allow Serato side A.

An option in a settings window would be adequate; as this is not going to be changed too often.

**Comment by danielhjames** [comment]
Serato side B works in relative mode by default. Ximo added CD timecode support in https://github.com/pideck/pideck/blob/master/timecode_select so let's test that.

**Comment by beaucasque** [comment]
@danielhjames so placing serato_b as a flag in the xwax command would make the same cd timecode work as relative. Right?

Thank you

**Comment by danielhjames** [comment]
See https://github.com/pideck/pideck/issues/121
