### ISSUE TITLE
Audio Output set to Raspberry headphones jack   

### ISSUE THREAD

**Issue by carlosguerra3** [pideck/pideck#25]
Is it possible to route the output audio to the Raspberry headphones jack instead of the USB card? 

Or the headphones jack under PiDeck/xwax is disabled?

**Comment by danielhjames** [comment]
Hi, to use a digital vinyl system you need a soundcard with full duplex stereo operation, i.e. the stereo input is opened at the same time as the stereo output. The Pi onboard audio that provides the headphone output is not capable of this. Also it is not very good quality in any case, see for example http://www.crazy-audio.com/2014/07/sound-quality-of-the-raspberry-pi-b/

Fortunately the I2S audio cards or USB interfaces which can do full duplex stereo are inexpensive and some of them already have the right connectors for turntables and mixers. Right now the cheapest option which works well with xwax in a single deck configuration is the American Audio Genie II USB.
