### ISSUE TITLE
Audio Injector card does not work with low buffer sizes

### ISSUE THREAD

**Issue by obbardc** [pideck/pideck#31]
below 16ms in Alsa mode the input signal is missing, producing the following error
![2016-11-25 14 43 06](https://cloud.githubusercontent.com/assets/1029590/20629580/3bd0d0cc-b324-11e6-9cf4-e310f64522d5.jpg)

**Comment by danielhjames** [comment]
https://github.com/raspberrypi/linux/issues/1321 implies this might only be a Pi 3 issue. We could try the audioinjector on a Pi 2 to be sure.

**Comment by danielhjames** [comment]
Fixed in Chris's 4.9 kernel package, audioinjector now works reliably at 4ms xwax buffer. Only one I2S sync error seen since.
