### ISSUE TITLE
design involvement

### ISSUE THREAD

**Issue by ptcampbell** [pideck/pideck#35]
Hi – love this project – thanks for making it!

Can't contribute much in the way of programming, but would love to offer my UI skills to the project.  

If you'd be interested in seeing a visual refresh at all I'd be keen to give it a shot.

Let me know.
Pat

**Comment by obbardc** [comment]
Hi Pat!

Hope you are well and you have managed to get pideck installed and working.

Please reply to this issue with any ideas, updates, notes, etc you may
have. We love any suggestions!!

Cheers!

Chris

**Comment by ptcampbell** [comment]
Not quite – still waiting on my Pi – so it's probably best to wait until I actually use it before coming up with any UX suggestions! 

Having seen the UI in the demo videos though got me thinking about a possible visual cleanup – e.g. some nice typography for the song-list view, a more distinctive waveform style – basically I was thinking we could give it a polish so it wouldn't look out of place next to say, Logic, Abelton or any other pro music software. 

Obviously I'm not quite across the technical limitations yet, but I'm sure we could design around them and come up with something cool.

**Comment by danielhjames** [comment]
Hi Pat, fonts and text sizes are defined in https://github.com/pideck/xwax/blob/touchscreen_gui/interface.c

You'll see more information in the GUI if your audio files are tagged with BPM etc. See http://www.pogo.org.uk/~mark/bpm-tools/

**Comment by ptcampbell** [comment]
Thanks. When I get set up I'll take a peek and get back. Cheers.
