### ISSUE TITLE
Waveshare 7 " display portrait mode BUT Audioinjector not working 

### ISSUE THREAD

**Issue by BennPaul** [pideck/pideck#43]
Hallo everyone,

thanks for this amazing project!

First: (to the display later more)

I have a problem concerning the audioinjector soundcard.

I installed the audioinjector card as said in:
http://www.flatmax.org/phpbb/viewtopic.php?f=5&t=3

an also with your option:
`alsactl restore --file /usr/share/pideck/soundcard.state`

on a fresh install of raspian lite with openbox/lxde

when I run 
`cat /proc/asound/cards` 

the outpunt is:

>0 [audioinjectorpi]: audioinjector-p - audioinjector-pi-soundcard
>                      audioinjector-pi-soundcard`
> 1 [JOCKEYINTERFACE]: USB-Audio - DIGITAL JOCKEY-INTERFACE
>                     RELOOP DIGITAL JOCKEY-INTERFACE at usb-3f980000.usb-1.5, full speed`

for testing purpose I have the USB-soundcard plugged in.

`aplay -l`
says:

>**** List of PLAYBACK Hardware Devices ****
>card 0: audioinjectorpi [audioinjector-pi-soundcard], device 0: AudioInjector audio wm8731->hifi-0 []
>  Subdevices: 1/1
>  Subdevice #0: subdevice #0
>card 1: JOCKEYINTERFACE [DIGITAL JOCKEY-INTERFACE], device 0: USB Audio [USB Audio]
>  Subdevices: 1/1
> Subdevice #0: subdevice #0

running pideck without your original script only the xwax option "--no-decor" disabled (because it is an unknown argument) it says for the audioinjector card:

> FOUND audioinjector-pi-soundcard

>number of supported cards found: 1
            
>Using -a hw:0 with 04ms Buffer
            
>Xlib.protocol.request.QueryExtension
>Xlib.protocol.request.QueryExtension
>pi@raspberrypi:/usr/share/pideck $ xwax 1.5 (C) Copyright 2014 Mark Hills <mark@xwax.org>

>This software is supplied WITHOUT ANY WARRANTY; without even the implied
>warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. This is
>free software, and you are welcome to redistribute it under certain
>conditions; see the file COPYING for details.

>Initialising deck 0 (hw:0)...
>ALSA hw_params: Invalid argument
>Failed to open device for capture.

WHY?

Starting xwax aka pideck with 
 >xwax -k -q 89 -g 860x600  -m 4 -r 48000 -a plughw:1 $LIBRARY &

then it really runs smoothly with the USB DIGITAL JOCKEY-INTERFACE.

Thanks again!

But i just bought the audioinjector for two reason:
1. The Mixer Line Bypass. Having the option to listen to records without unplugging
2. The size compared to my USB soundcard
So, I really want to get it running!

A strange behaviour is, every time I start alxamixer it opens with PulseAudio card.
When I switch manually to audioinjector Bypass is working so I think the card is fine.
But why alsamixer doesn't open directly with audioinjector?

I tried some option and tweaks in the /boot/config.txt no results.

In audacity (on the same OS) I tested the audioinjector card. It is possible to set it as card for playback an record. But it doesn't record anything?! The USB-card records as expected.

Has anyone an idea? Help? please!

Second:

I also just bought a Waveshare 7 " display with 1024x600 resolution for the pideck raspi.
It is running via HDMI so it is possible to have a longer cable and therefore more distance to the raspi. I'll mount it on a gooseneck to have it directly over the turntable.

For me it is a good idea to use it in portrait mode, so there is more space for the playlist. On the bottom I'll place the commonly used buttons. On top the ones one don't need so often, like rescan an record. 
I already tested it, with the resolution of 600 in width it is really nice for playlist.

When it is finished I'll commit the code if liked?

But the soundcard took me hours so far, sorry.

Thanks in advance!

Ben

**Comment by obbardc** [comment]
Hi Ben

Please try our Raspberry Pi image with all the tweaks added: http://ares.djz.us/~chris/pideck/staging/pideck-staging.img.zip

**Comment by BennPaul** [comment]
With this image the audioinjector card worked out of the box. Thanks! 
It tested the card on a full raspian installation also. It behaves the same as on the raspian lite version. Playback working but recording not (tested again with Audacity). Hope to get it working on these to images, too. Anyone an idea?
A question about the behaviour of the card with pideck:
When turn the Bypass volume potentiometer up or down on the soundcard it influences the quality of the signal for reading the timecode signal, as can be seen on the xwax gui.
I thought it will give the signal from the record to the speakers without influencing the volume level in the software. 
Is this its normal behaviour?
So it is really complicated to switch between normal records and timecode control because one always needs to mute the volume in alsamixer.
A switch for this would be a nice new button for the pideck gui.

**Comment by obbardc** [comment]
The Pideck package only supports our custom Debian image. It probably won't
work as expected in Raspbian.

Good idea about the bypass button.

I will add this as a separate issue.

**Comment by danielhjames** [comment]
Hi Ben, recording should work if you can find the correct input device in the Audacity preferences and unmute any capture channels in alsamixer. I had Audacity working with the audioinjector here, but I found the GUI a little cumbersome with the small touchscreen. For a simple recorder I prefer butt: http://danielnoethen.de/

As for the potentiometer on the side of the audioinjector, I don't think this is related to the bypass control. I think it is a level input trim. Set too low, this will definitely affect xwax performance, because a good loud timecode signal is required. I suggest you leave it on maximum unless you are recording a loud analogue record and experiencing clipping. Even then, you should probably reduce the gain on your phono preamp to allow more headroom on the audioinjector input, as gain added in the pre-amp also increases vinyl surface and background noise, of course.

**Comment by BennPaul** [comment]
Hey Daniel,
thanks for your answer!
Recording (with Audacity) works now. Audacity was just for testing purpose because I used it before. I missed the capture option in alsamixer first. 
But it seems that the settings are not saved. I tried alsactl store, but after rebooting capture mode isn't set anymore. 
And I have also no reaction when I try to run xwax.
I start it with:

`xwax -l /media/usb0/Music/ -a hw:0`

It is starting up, but no signal. Has anyone an idea?
Same with pideck. There I get the message:

> Initialising
> deck 0 (hw:0)...
>ALSA hw_params: Invalid argument
>Failed to open device for capture.


Which ALSA hw_params are right and where to find it?

I really wanted to get it running on raspian lite. The reasons are some disadvantage I had with the pideck-distro:
#Edit### Display is working now ########
1. The waveshare display dosn't work. (http://www.waveshare.com/wiki/7inch_HDMI_LCD_(C))
######################
2. I didn't get wifi running. I need it for ssh. Sadly no option for LAN-cable.
3. couldn't expand the filesystem on the sd card. No fdisk and resize2fs. The smallest SD-card I could get was 16 GB, enough space for some tunes.
(edit: 4. and use it as a internet radio in the future without switching sd cards)
EDITED AGAIN:  Having 1.-3. in pideck-distro would be awesome!

For the pideck installation I cloned https://github.com/pideck/pideck.git
and ran the commands of your build file.

Thanks in advance!

**Comment by BennPaul** [comment]
> As for the potentiometer on the side of the audioinjector, I don't think this is related to the bypass control. I think it is a level input trim.

I thought the potentiometer is for bypass control, when I read about audioinjector before I ordered it. But input level is also a good option for the potentiometer ;-)

With my USB-card xwax works just fine on my raspian lite system. So I think building it worked. I started from a fresh system, only installed X-server and some lxde basics first. But I installed the audioinjector after pideck, because I didn't had it at the time I installed pideck.

**Comment by BennPaul** [comment]
The display is running, I copied the wrong /boot/config.txt first.
With: 
> max_usb_current=1
hdmi_group=2
hdmi_mode=87
hdmi_cvt 1024 600 60 0 0 0
display_rotate=1

it runs.

I made a bottom and a top row for the buttons, and placed the more often used "transport control buttons" on the bottom, the others on top, including a bypass button. See issue #44 for more details.
 
This is all just a first try. I'll soon upload the scripts, if wanted?

See pictures of portrait mode below.

![img_20170211_005350](https://cloud.githubusercontent.com/assets/25537656/22848906/c75c9be6-efef-11e6-9bb1-dded8cae02b8.jpg)
![img_20170211_005402](https://cloud.githubusercontent.com/assets/25537656/22848902/c355f5c4-efef-11e6-8e7f-116c4c8e3f40.jpg)

**Comment by danielhjames** [comment]
Please do contribute the scripts! I like the ergonomics of where you have placed the display, easy to see but not between you and the audience.

Incidentally, you can get a better library display if your files are tagged with title, artist and BPM information and you use a script such as http://wiki.xwax.org/mark_scan_tags

**Comment by BennPaul** [comment]
Hi,

the zip-file contains the scripts for using pideck with the Waveshare 7" LCD 1024x600 Rev 2.1 display.

I really spent too much time for the right set-up of the touchscreen controls in portrait mode. xinput_calibrator and tweaking some config files didn't do the job successfully. 
In the end I came up with maybe the easiest solution: I added two commands in the pideck_VERT script. 
After running the pideck_VERT script now everything is fine in portrait mode.

The button size and the xwax windows are working good together on my screen, although they are not representing the real real estate of the screen. I have no clue why simple addition is just an estimation here.    

Landscape and portrait mode added, see the config.txt for a short description: 
[config.txt](https://github.com/pideck/pideck/files/775025/config.txt)

replace the config.txt with the original /boot/config.txt and make the pideck_* scripts executable in the /usr/share/pideck folder

[PiDeck_Wavshare_display.zip](https://github.com/pideck/pideck/files/775073/PiDeck_Wavshare_display.zip)

Hope it helps!

something like a BUG:

When I have a USB stick in the raspberry while booting the pideck distro, it won't boot.
Same USB stick with raspian PIXEL or raspian lite, it boots flawlessly.

**Comment by danielhjames** [comment]
Thanks for the scripts! As for the booting issue, I had not experienced that. Does your USB stick contain any bootable files? I'll open a ticket in an attempt to reproduce the issue.

**Comment by danielhjames** [comment]
I wonder if you have modified the /boot partition at some point and it is looking for a root filesystem on the USB stick instead of the micro SD card?

**Comment by kyleatblackfoot** [comment]
Hey BennPaul, I have a question relating to using both the Waveshare screen and the AudioInjector, my intention is to mount the display onto the GPIO pins on the AudioInjector, do these two components work together, they don’t clash? I want to confirm before buying the  sound card. Thanks
