### ISSUE TITLE
Sound card without  phono preamp

### ISSUE THREAD

**Issue by FelipeAlme** [pideck/pideck#48]
My turntable has an internal amp, I have a UCA 200 card, what should I do to be able to use the "Pideck"?

**Comment by danielhjames** [comment]
Hi, if your turntable has a line output, it should connect directly to the UCA 200 with the correct level. If you hear the control signal routed to the audio output, you may need to perform a mod similar to this one: http://www.mixxx.org/forums/viewtopic.php?f=6&t=2438&sid=72208f0cb2ced9fd785ba3b81ab5e147

**Comment by FelipeAlme** [comment]
Do I have to make any changes in my pideck?

I put my UCA 200 on the raspberry but XWAX does not open

**Comment by danielhjames** [comment]
Are you using the 0.1 release? If so, please try the latest testing image:

http://ares.djz.us/~chris/pideck/staging/pideck-staging.img.zip

This has better detection for alternative soundcards.

**Comment by FelipeAlme** [comment]
I bought my raspiberry a week after you posted the first video on the channel, I would like to thank you finally after a long time trying to get it to work, thank you sir, you do not know how you helped me, this will be fundamental for my Growth with dj

**Comment by FelipeAlme** [comment]
Thank you very much, I will make a video in Portuguese today explaining how it works :D

**Comment by danielhjames** [comment]
Great, please let us know the URL so we can add it to our YouTube channel!
