### ISSUE TITLE
WM8731 level balance issue on input & output

### ISSUE THREAD

**Issue by obbardc** [pideck/pideck#6]
Left output channel has consistently louder signal on mixer. Input scope in xwax is oval, showing an input channel mismatch too.

**Comment by obbardc** [comment]
This is now apparently fixed in the Pi Kernel Fork. See: https://github.com/raspberrypi/linux/commit/8181728d2cb33ea914dc626f2489b597599102df

**Comment by danielhjames** [comment]
Nice! Where it says "This ensures that channel 2 doesn't loose any bits during capture", I wonder if this could be related to the cause of the DMA error messages? Perhaps these errors don't show up in playback-only use cases? After applying this patch we could try a smaller xwax buffer.

**Comment by obbardc** [comment]
Hi Daniel,

Please see here for the latest Pideck with fresh compiled Kernel:
http://djz.us/~chris/pideck/distro/

I have tested it works on our Pi hardware but have not tried with the
soundcard.

Could you check if we still get DMA error messages & also sound issues with
this build?

**Comment by obbardc** [comment]
Fixed in upstream Raspberry Pi kernel as linked above.

**Comment by danielhjames** [comment]
I'm sure the levels are closer to matching now but I will run some more accurate tests, there may be further improvements to be made here.
