### ISSUE TITLE
ESI Maya44 USB "2 channel audio not available on this device"

### ISSUE THREAD

**Issue by AdrianTP** [pideck/pideck#62]
Howdy,

I have the latest release (koolherc) downloaded from the website about a week ago, and I am having similar issues to those encountered by @EvMueller in https://github.com/pideck/pideck/issues/24. Following the steps outlined in that conversation, I ran:

```sh
xwax -k -q 89 --no-decor -m 3 -r 48000 -a hw:1 -l /media/usb0/Music
```

and I received the following output:

```sh
Initialising deck 0 (hw:1)...
ALSA hw_params_set_channels: Invalid argument
2 channel audio not available on this device.
Failed to open device for capture
```

I know for a fact that 2-channel audio *is* available on this device ([ESI Maya44 USB](http://www.esi-audio.com/products/maya44usb/) -- in fact it has 4 inputs and 4 outputs, for dual stereo in and dual stereo out, as well as a dedicated optical/3.5mm stereo monitoring port), and I have successfully used it for DVS and multichannel audio IO on Mixvibes Cross DJ on Android, Mixxx on Mac, and MsPinky's Maxi Patch on Mac.

Is this device just not class-compliant, or is there something else going on? I know back when I first started using it I had to install a custom control panel for it (back on OS X 10.4 and 10.5), but now my Mac (OS X 10.11) and my Android (v7 Nougat) both recognise it just fine and can even natively control the levels on each individual input and output channel without any drivers or control panels or helpers installed.

Am I missing something?

If it's something wrong with my USB audio card, then I am not opposed to purchasing a Behringer U-Control or even an AudioInjector, but I figured I would just test it with what I already have on-hand so I can decide whether to invest in this system as my primary DVS setup, or carry around a laptop and use Mixxx or MsPinky.

**Comment by danielhjames** [comment]
Hi Adrian, this error just means that your device has more than two channels, so xwax cannot find the stereo device it is expecting. One way around this is to use an ~/.asoundrc file to create stereo pairs, for example: http://www.pogo.org.uk/~mark/linuxdj/maya44.asoundrc

**Comment by AdrianTP** [comment]
Oh that's great thanks. I will give that a go and check back with the results. 👍

**Comment by AdrianTP** [comment]
I gave it a shot with the `~/.asoundrc` file and it seems to have had no effect. I still receive the same output when running the command I specified in my first comment. Perhaps I am missing some prerequisite?

**Comment by danielhjames** [comment]
Instead of using the hw:1 parameter for the hardware device, try using one of the virtual devices specified in the .asoundrc file. For example, maya44_pair1

**Comment by danielhjames** [comment]
Instead of using the hw:1 parameter for the hardware device, try using one of the virtual devices specified in the .asoundrc file. For example, maya44_pair1

**Comment by AdrianTP** [comment]
That did it!

`xwax -t serato_cd -m 15 -r 48000 -a maya44_pair1 -t serato_cd -m 15 -r 48000 -a maya44_pair2 -k -q 89 --no-decor -l /media/usb0/Music`

Two questions remain:
- How would I make this the automatic startup procedure so all I have to do is plug it in?
- How do I route audio output? The output is not coming from the RasPi's onboard audio jack, nor is it coming from the outputs on my Maya44. Basically I just want to test this a little bit before I go buy a Behringer UCA222 (which I assume works "automagically").

Thanks so much for all your help so far!

**Comment by AdrianTP** [comment]
Ok after reading around the net a bit I discovered that it might simply be a volume issue. I was right -- the default volume on the outputs is apparently -24 dB, so I simply need to figure out the correct ALSA config to turn up the volume on the outputs the same way it was done for the inputs. Sure enough, when I plugged my speakers into the output and cranked the volume on my speakers to maximum, I could hear some quiet music playing when the deck was spinning. Time to experiment.

**Comment by danielhjames** [comment]
alsamixer should enable you to set the output volume to the level you need.
To make this xwax command automatic, you will need to edit the main /usr/share/pideck/pideck script.
As for buying the Behringer card, you may not gain any benefit from that, as your existing card has more I/O.

**Comment by AdrianTP** [comment]
I thought `alsamixer` was just broken or something because it kept returning `cannot open mixer: No such file or directory` but upon more searching, I discovered I have to pass a parameter. `alsamixer -c 1` enabled me to turn up the volume. Unfortunately that volume setting does not persist after a reboot. Is there any way for me to get that to stick?

**Comment by danielhjames** [comment]
Please try the command:
sudo alsactl store

**Comment by AdrianTP** [comment]
It would still not persist through a reboot. I ended up following a combination of steps from [this askubuntu thread](https://askubuntu.com/questions/50067/howto-save-alsamixer-settings):

`alsactl --file ~/.config/asound.state store`

and added the following to the end of my /usr/share/pideck/pideck, after commenting out the default "start xwax" parts:
```sh
sudo alsactl --file ~/.config/asound.state restore
xwax -t serato_cd -m 15 -r 48000 -a maya44_pair1 -t serato_cd -m 15 -r 48000 -a maya44_pair2 -k -q 89 --no-decor -l /media/usb0/Music
```

...but it still won't load my alsa settings unless I manually open a terminal and call `sudo alsactl --file ~/.config/asound.state restore`.

**Comment by danielhjames** [comment]
See the file https://github.com/pideck/pideck/blob/master/soundcard-setup.service - we save the soundcard state to a system file rather than a file under the home directory. Probably using sudo inside the main pideck script will not work, as there is no way to prompt you for the password.

**Comment by AdrianTP** [comment]
```sh
sudo mv /usr/share/pideck/soundcard.state /usr/share/pideck/bak-soundcard-state-bak
sudo ln -s ~/.config/asound.state /usr/share/pideck/soundcard.state
```

^ that did the trick 😄

**Comment by AdrianTP** [comment]
I am going to go ahead and close this since my issue is resolved. Hopefully this log will help others reach similar conclusions.
