### ISSUE TITLE
PiDeck for OrangePi and other boards

### ISSUE THREAD

**Issue by K3nn3th2** [pideck/pideck#64]
Hey Folks,

it would be great to have PiDeck versions for the OrangePi and possibly other mini boards aswell.
shouldn't the distro-builder be configurable to achieve this?

thanks!

**Comment by danielhjames** [comment]
Thanks for getting in contact :-) I think we would need some performance test results from other boards and soundcard combos to see if the overhead of supporting them had enough benefit. If the board in question is simply a Raspberry Pi clone it may not have anything special to offer.

**Comment by K3nn3th2** [comment]
The orange pi offers more bang for the buck and the banana pis are available with more performance. This would probably enable additional audio processing in the jack chain without any trouble. An example: effects using midi controllers and FX software. 
i believe the orange pi can run raspbian (maybe a port?) and as pideck is raspbian based maybe its not too much to be modded for it to work?

**Comment by danielhjames** [comment]
Please give the PiDeck image a try and let us know if it works. Thanks!

**Comment by romansavrulin** [comment]
@danielhjames, @K3nn3th2  Orange Pi uses another kernel - [linux Sunxi](http://linux-sunxi.org/), so at least kernel rebuild is needed. Hopefully, you can get this kernel as a binary from [Armbian images](https://www.armbian.com/download/). Don't forget the modules too.

And you need to select proper compatible CPU architecture to use same root filesystem. From the first sight Oranges based on [H5 CPUs](http://linux-sunxi.org/H5) should be compatible with [RPi3 models](https://en.wikipedia.org/wiki/Raspberry_Pi) as both uses quad-core ARM Cortex-A53.

**Comment by obbardc** [comment]
This is something we plan on doing, but there are a lot of different Allwinner boards out there. Have you got any specific boards in mind?
