### ISSUE TITLE
Second soundcard and touchscreen buttons [SOLVED]

### ISSUE THREAD

**Issue by GuusR** [pideck/pideck#65]
Hi all,

I have issues with getting pideck running with two sound cards. I have two behringer ufo202's (both modified for hardwire issue) and a raspi3 with touchscreen. Both soundcards are tested and working.
Xwax won't boot if just one of either soundcards is connected. When I plug in both soundcards xwax starts but only one with one deck. When checking alsamixer it shows only one PCM out channel, but both cards are recognized in cards as 0 [CODEC_1]  and 1 [CODEC] respectively. 
A generic chinese 2 in 2 out card is not recognized at all.

Any ideas on how to get both cards running and get xwax to run with two decks? All help is much appreciated!

**Comment by danielhjames** [comment]
Hi, to use two sound cards per Pi you need to modify your xwax start up command in the script /usr/share/pideck/pideck

Each sound card must be specified individually. First, find your card numbers from the command:

arecord -l

Then refer to http://wiki.xwax.org/writing_your_start-up_command for the appropriate options.

alsamixer may be misleading here, it will open card 0 unless you specify the -c parameter, e.g. alsamixer -c 1 opens the second card in the system.

**Comment by GuusR** [comment]
The project has been on the shelf for a while and finally found time to work on it again. Thanks for the reply @danielhjames! With some help of a mate I've managed to modify the start up command and get it to work with two sound cards.

Just one issue remains though, I only have one load button on the touch screen button row. So as of now I can only load tracks to deck 1 via the touch screens commands. How can I get both load 1 and load 2 buttons to show up on the touch screen?

FYI: all I've done now is insert -a hw:0 -a hw:1 in the start up command

**Comment by obbardc** [comment]
Hi Guus,

You can use a qwerty keyboard connected to the Pi to control xwax. The
keybindings are here: http://wiki.xwax.org/keyboard_control

So if you can press F5, and all loads OK, try modifying the script which
makes the buttons appear.

The file that shows the menubar, when pressed sends a keyboard press event
to xwax, is located /usr/share/pideck/touchscreen_controls*

Let us know how you get on, would be interested to get your thoughts on the
right screen layout for a two-deck setup as I know @danielhjames is playing
about with a two-deck setup....

Cheers!

**Comment by GuusR** [comment]
Hi Chris,

Thanks for the fast reply! 
I've tried to load using f5 on the keyboard but that didn't seem to work. But none of the keyboard controls work for xwax so that's another issue I guess. Could be an issue of this specific keyboard, but it works to get in terminal so thats a blessing.

Anyways, I think all should work if I can get that second load button (and perhaps cue2 button) on the screen. I've poked around in the /usr/share/pideck/touchscreen_controls but python is new for me so I couldn't figure out what to change in the script.

Could anyone share the right touchscreen_controls script to get those load2 and cue2 buttons to show up?

Cheers!

**Comment by GuusR** [comment]
@obbardc I think this would be a neat screen layout but that's just my first thought. No clue on how hard it is to resituate buttons to another part of the screen though.

![touchscreen](https://user-images.githubusercontent.com/25119480/34434103-184fa50c-ec84-11e7-996d-b5e6c1553451.jpg)

**Comment by obbardc** [comment]
I think that issue is because the focus is not on the xwax window. Can you
use a mouse and click on xwax, before hitting the keyboard button?

Great idea about the buttons. We have a few ideas, I'm terrible at choosing
but @danielhjames will be the one to choose :-)

We are thinking of having dual-turntable support built in, with some kind
of auto-detection or settings window where you can choose.

PS. 2 Bad Mice - Bombscare awesome choice...!

**Comment by GuusR** [comment]
Ah yes, clicking xwax got the keyboard controls going, and all works well as far as I can see now!
So I understand the extra touch buttons are a work progress as of now?

PS. haha, first music folder I could find on my laptop, sweet rave music :)

**Comment by obbardc** [comment]
Yeah, but like I say you can modify the code in the file I liked above to
add your own or change it, it shouldn't be too mental to change the button
text and action :).

The best way would be some kind of configuration file, so we can have
different buttons for different setups.

My idea is you would choose this on boot, or it autodetects from the number
of channels available...

Really it's whatever you want us to do, since you're the users

Cheers!

**Comment by GuusR** [comment]
I think it would be nice to have the touchscreen script check the startup script for a hw:1. If that is defined it should accommodate two load and cue buttons.

As I said I'm fully new to python so don't expect much. What I'm going to try now is change the touchscreen_controls on my pi and modify the 'rescan' and 'timecode' buttons and use those for cue2 and load2. That way I don't have to add any code, just edit a little bit. Which I think is a good first step into python ;)

I'll keep you updated! Cheers

**Comment by GuusR** [comment]
I got it working! Rescanning or changing the timecode has to be done via a keyboard, but for basic mixing all controls are on the screen now. All I've done is change the definitions of the keys and the names, easy workaround I guess :)

Thanks so much for the help Chris! Next step for me will be getting the folder to crate function to work.

PS. Is the load button (f1) defined two times on purpose? Just wondering why that command is in the touchscreen code twice.

![img_4482](https://user-images.githubusercontent.com/25119480/34437064-509b6394-ec9b-11e7-9b5d-f58837b83dee.JPG)

**Comment by danielhjames** [comment]
Hi, great to hear you got two decks working :-) In the latest version on GitHub we have left and right touchscreen controls, for example: https://github.com/pideck/pideck/blob/master/touchscreen_controls_L

This creates more vertical space which allows more tracks to be shown in the library view. But that really depends on what size screen you are using.

btw it's been so long since I heard Injected with Poison that I had to go listen on YouTube :-)

**Comment by GuusR** [comment]
Hi James, that's a nice solution to get some extra room on the screen. Eventually I will try to get everything to work with dicers and maybe a rotary encoder but those are for the dar future.

I'm now struggling to put it in absolute mode. I like to just put my needle back to go to the start of a track, but I can't find the right start up command for this function in xwax. Any ideas?

**Comment by obbardc** [comment]
Try swapping the record to the other side ;-)

**Comment by GuusR** [comment]
@obbardc Thanks for the tip! Switched to the a-side and now it does absolute positioning, thanks!
