### ISSUE TITLE
Compile xwax deb with our touchscreen_gui mods applied

### ISSUE THREAD

**Issue by obbardc** [pideck/pideck#7]
Also maybe post some information on how to cross-compile using pbuilder so we can setup an auto-package-builder from Github hooks?

**Comment by obbardc** [comment]
https://github.com/pideck/xwax/commit/f562a3851caa8a589033206398b874844c7742a0  commit is wrong.

**Comment by danielhjames** [comment]
Fixed in https://github.com/pideck/pideck-debs/commit/22f25a1aa1d1d59295014abf64369d9def60761b

See http://manpages.ubuntu.com/manpages/precise/man1/cowbuilder-dist.1.html for details of pbuilder-dist. An auto-builder would probably be overkill at this stage for one or two packages.
