### ISSUE TITLE
Controller jog wheels vs Vinyl

### ISSUE THREAD

**Issue by DJRickPalacios** [pideck/pideck#71]
Hi Daniel, love the project, have been a fan from its inception, Great Work. So I have 3 controllers sitting around, VCI-100 (original), m-audio Xponent and traktor S4 mk2. Will these work with pideck project using the jog wheels instead of turntables?

**Comment by danielhjames** [comment]
Hi Rick, there is no built-in support in xwax for this type of controller, but you could probably run Mixxx on the Raspberry Pi 3 using the PiDeck release as a base. See for example https://www.mixxx.org/wiki/doku.php/native_instruments_traktor_kontrol_s4_mk2

**Comment by obbardc** [comment]
We don't have plans to add support for controllers in the pideck project. Sorry!
