### ISSUE TITLE
Audio is very fast and warbley

### ISSUE THREAD

**Issue by Rikroka** [pideck/pideck#83]
Firstly thank you for making this wonderful project!

I'm using a NI Audio 8 with the Traktor Control Vinyl MK2 and PiDeck plays back audio very fast and the pitch is warbling loads. Do you know what's wrong?

**Comment by danielhjames** [comment]
Hi @Rikroka the Traktor Mk2 vinyl is not supported by xwax, I would recommend using Serato CV02 or CV02.5 vinyl for best results. If you are interested in hacking on support for Traktor Mk2 vinyl please subscribe to the xwax mailing list https://sourceforge.net/projects/xwax/lists/xwax-devel and post your findings there. Cheers!

**Comment by Rikroka** [comment]
Doh! Serato vinyl ordered. Thanks again, this will breath new life into my old 1210s!
