### ISSUE TITLE
Audio crackles and warbles

### ISSUE THREAD

**Issue by Rikroka** [pideck/pideck#86]
So I now have the Serato control vinyl (with a Pi 3 and a NI Audio 8) and things are working!

However  the pitch warbles a bit, sometimes it doesn't but often it does. I've ordered some new sytli in case that helps, or is not not possible to cause pitch flutter? What should I do?

The audio also crackles, I read with other software increasing the buffer may help, how would I do that?

Thank you!

**Comment by obbardc** [comment]
Can you see on the screen there is a number somewhere fluctuating around
"1.000"?

that corrosponds to the recognized pitch & should be as close to 1 as
possible.

How is the pitch adjust red light looking?

I have had some cheap turntables with a bad mechanism/motor that simply
couldn't keep speed.

Cheers!

chris

**Comment by Rikroka** [comment]
These are rock solid 1210s- there's no pitch warble with "real" vinyl.

There's no number like what you're talking about that I can see, just the tracking wheel and rotating line and the time... (I'm using PiDeck 0.2 if that makes a difference)

Cheers

**Comment by Rikroka** [comment]
Solved it! The Pi wasn't getting enough power- I connected the Audio 8 via a powered usb hub and everything works perfectly!

This is the best Pi project ever, thank you!

![20181026_165820](https://user-images.githubusercontent.com/17595784/47597434-932c7280-d943-11e8-9566-901776100440.jpg)
(Yes I need to sit on the floor)

**Comment by obbardc** [comment]
So cool!!!
Thanks for sharing with us.
