### ISSUE TITLE
Wrong password for sudo - Can't edit config

### ISSUE THREAD

**Issue by MrShigura** [pideck/pideck#88]
Not sure what I'm missing here but when I get a terminal open and try to sudo into /boot/config.txt, I'm told I'm using the wrong password for user pi (raspberry) and I'm unable to edit it to rotate the display.

**Comment by obbardc** [comment]
Try deck as the password?

Maybe Dan has some more info on this ;-)

**Comment by danielhjames** [comment]
Sorry about that, I forgot to put the new password in the release notes. https://github.com/pideck/pideck-distro/releases/tag/v0.2-alpha has been updated.
