### ISSUE TITLE
IN NEED OF SOME ADVICE.

### ISSUE THREAD

**Issue by raynessupreme** [pideck/pideck#92]
Hi everyone. I think I have finally got my head around GitHub and found how to post to the forum! Apologies to the creators of PiDeck and xWax for the emails sent to them, especially after I was redirected to GitHub from them.

First of all a big thank you for your hard work on this project. This being one of the sole reasons I purchased a Raspberry Pi.

As a beginner to Linux I have had to get my head around things fairly quickly. After mucking around with the 0.1 release I managed to open the terminal and add in my soundcard configurations (Behringer UFO 202) as it would not automatically show on startup. However the audio quality of said soundcard was a nightmare, so back to the drawing board I went, plus I cannot remember how I even opened the terminal and changed the script. I tried this on the 0.2 release for my newer four channel soundcard by pressing F10 and going via the "sudo nano usr pideck" directory, but when I managed to open that up I got quite lost. Haha!

In an attempt to learn more about xWax I multi-booted my Windows PC with Ubuntu and compiled xWax. In the last couple of days I have configured both my Mixvibes UMix44 soundcard with my Novation Dicers and things seem to run as they should. The latency is insane on this open source software.

Now that I have figured out how to compile and work xWax in Ubuntu I now need to implement this into PiDeck. My first query is how do I locate or where do I add in my .asoundrc file so my soundcard is picked up on startup? Also, where do I add in my startup configurations that I would usually type into the terminal to launch xWax? My Ubuntu launch script is "sudo xwax -l ~/audio --line -m 16 --dicer hw:Dicer -a umix44_pair1 -a umix44_pair2", so presumably all I would need to modify would be the audio location to my USB drive plugged into my Pi and I should be good to go,

Any feedback is appreciated. I would like to hope after figuring out how to sort these queries out I should have the PiDeck running a treat. After trawling the forums on here I liked the customisation of the E-xWax in Issue #66 - has this been implemented into the 0.2 release I have on my SD card? I would like to hope so given the various YouTube videos I have watched over the past year regarding the 0.2 release. I like the idea of BPM detection, vinyl flip for cueing the next song as well as the Dicer upgrades in the software. I couldn't get my head around reading the original GitLab post from the author of E-xWax about making branches from their repository into your own installation of xWax. Again, I'm just a Linux n00b. Haha!

Finally, if you are able to add in the .asoundrc configuration for the Mixvibes Umix44 USB Soundcard for auto detection I would be greatly appreciative. The script is as follows...

pcm.umix44_capture {
     type dsnoop
     ipc_key 1646
     slave {
         pcm "hw:Device"
         period_size 0
         buffer_size 65536
         rate 44100
         channels 4
     }
}

pcm.umix44_playback {
	type dmix
	ipc_key 1646
	slave {
		pcm "hw:Device"
		period_size 0
		buffer_size 65536
		rate 44100
		channels 4
	}
}

pcm.umix44_duplex {
	type asym
	playback.pcm umix44_playback
	capture.pcm umix44_capture
}

pcm.umix44_pair1 {
	type plug
	ttable.0.0 1.0
	ttable.1.1 1.0
	slave.pcm umix44_duplex
}

pcm.umix44_pair2 {
	type plug
	ttable.0.2 1.0
	ttable.1.3 1.0
	slave.pcm umix44_duplex
}

As an additional request, the audio output on my Umix 44 is ridiculously quiet. If Anyone has any knowledge on how to rectify this I would be appreciative. 

Many Thanks in advance.

Shaun.

**Comment by raynessupreme** [comment]
As an additional request, the audio output on my Umix 44 is ridiculously quiet. If Anyone has any knowledge on how to rectify this I would be appreciative. 

Thank you.

**Comment by danielhjames** [comment]
Hi @raynessupreme the file to look at is [cards_autodetect](https://github.com/pideck/pideck/blob/master/cards_autodetect)

For special soundcard setups we first check the detected hardware from the file `/proc/asound/cards` in line 33 onwards, then use the conditionals from line 112 onwards.

We copy a custom file into the `.asoundrc` (for example `/usr/share/pideck/Mk2.asound.conf`) and set up the touchscreen buttons for the hardware, depending on features. The generic buttons for two decks use the 'twindeck' argument.

Finally from line 164 onwards we boost volume levels for known quiet cards to maximum. Use a command such as:

`amixer -c 0 sset PCM 128` 

to find the maximum number your hardware will accept, for example for the first soundcard '0' where the output is labelled 'PCM' in alsamixer. You may see output such as:

```
Simple mixer control 'PCM',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 110
  Mono:
  Front Left: Playback 110 [100%] [0.00dB] [on]
  Front Right: Playback 110 [100%] [0.00dB] [on]
```
...indicating in Limits: that the maximum value for my particular hardware is 110. If you specify a higher number you will get the max 100% value.
