### ISSUE TITLE
Should the release key be F10?

### ISSUE THREAD

**Issue by danielhjames** [pideck/pideck#94]
https://github.com/pideck/pideck/blob/bf0d4383c611cbeb3ca353fadc028e2e73c23a36/touchscreen_controls_L#L102

**Comment by obbardc** [comment]
Oops!  =)

it should be F10, going by the logic of `function_key=2+deck*3`

**Comment by danielhjames** [comment]
There is a clash between our shortcut for opening a terminal and xwax's default shortcut for cueing a third deck, both of which are on F10. As we don't support a third deck in our touchscreen config, I'm happy to remove this part.
