### ISSUE TITLE
Behringer UCA222 has varying ID strings

### ISSUE THREAD

**Issue by danielhjames** [pideck/pideck#95]
Sometimes it identifies itself as:

USB AUDIO CODEC

and other units with a different capitalisation:

USB Audio CODEC

Looks like Behringer removed the chipset vendor name from the string. So we will need a new conditional in the cards_autodetect script to load up a twin deck configuration when two UCA222 are used.

**Comment by obbardc** [comment]
Can you check the string equality without case sensitivity?

**Comment by danielhjames** [comment]
Good idea, we can use the grep -i argument. Previously we have checked for strings such as 'BurrBrown from Texas Instruments' but for some reason Behringer units with the same chip do not display these words.

**Comment by obbardc** [comment]
Does lsusb contain any useful information?

**Comment by danielhjames** [comment]
Hi @obbardc I don't have this hardware but have updated the generic twindeck config to match a pair of devices with either 'USB AUDIO' or 'USB Audio' in the vendor strings. That should match a pair of UCA222 and other devices too.
